###############################################
#                Caesreon Shops               #
###############################################
allgemein:
  aktiviert: true
  version: 1
  prefix: '[Shop]'
  regex: 'ยง'
text:
permissions:
  spieler: 'caesreon.commands.shops'
erlaubte_welten:
  - 'Malmundus'
  - 'Orsoy'
  - 'Ceres'
schilder:
  beschriftungen:
    kaufen: '[Kaufen]'
    verkaufen: '[Verkaufen]'
    adminShopKaufen: '[A-Kaufen]'
firmenbezeichner: '[Warenhaus]'